booksforbrain/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
urlpatterns = [
    path('signup/', registrationForm, name='signup' ),
    path('login/', loginPage, name='login' ),
    path('logout/', logOut, name='logout' ),
    path('', home, name='home'),
    #requires id
    path('book-detail/<int:id>', bookDetail, name='book-detail'),
    path('owned/', ownedBook, name='owned-book'),
    path('publish/', publishBook, name='publish-book'),
    path('update-book/<int:id>', UpdateBook, name='update-book'),
    path('delete-book/<int:id>', DeleteBook, name='delete-book'),
]

booksforbrainapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('booksforbrain.urls')),
    path('admin/', admin.site.urls),
]

booksforbrain/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    GENRES = (
        ('Bibles', 'Bibles'),
        ('Computer', 'Computer'),
        ('Encyclopedia', 'Encyclopedia'),
        ('History', 'History'),
        ('Language & Literature', 'Language & Literature'),
        ('Mathematics', 'Mathematics'),
        ('Medical', 'Medical'),
        ('Psychology', 'Psychology'),
        ('Science', 'Science'),
        ('Social Science', 'Social Science'),
        ('Technology & Engineering', 'Technology & Engineering')
    )
    book_image = models.URLField(max_length=200)
    book_name = models.CharField(max_length=100)
    book_author = models.CharField(max_length=100)
    price = models.FloatField()
    genre = models.CharField(max_length=100, choices=GENRES)
    description = models.TextField()
    quantity = models.PositiveIntegerField()
    book_link = models.URLField(max_length=200, blank=True)
    date_published = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.book_name

class OwnedBook(models.Model):
    OWNED = (
      ('not owned', 'not owned'),
      ('owned', 'owned')
    )
    reader = models.ForeignKey(User, related_name="owned", null=True, on_delete=models.SET_NULL)
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL)
    date_sold = models.DateTimeField(auto_now_add=True)
    owned = models.CharField(max_length=100, null=True, choices=OWNED, default='not owned')
    

    

booksforbrain/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *


class RegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class PublishBook(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

booksforbrain/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import *
from .models import *
from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .filter import BookFilter
from django.contrib.auth.decorators import login_required
from .decorators import *


# Create your views here.
@unauthenticated_user
def registrationForm(request):
    form = RegForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name="bookreader")
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            messages.success(request, "Account created for Reader " + username + " ✔️")
            return redirect('login')
        

    context = {
        'form': form
    }
    return render(request, 'signup.html', context)

@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, 'Check out your books')
            return redirect('home')
        else:
            messages.error(request, 'Username or password incorrect 🤔')

    return render(request, 'login.html', ) 

def logOut(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def home(request):
    
    all_books = Book.objects.all()
    book_filter = BookFilter(request.GET, queryset=all_books)
    all_books = book_filter.qs
    books_available = all_books.count()
    ownedbook = OwnedBook.objects.all()
    books_sold = ownedbook.count()
    group = User.objects.filter(groups__name='bookreader')
    readers = group.count()
    
    context = {
        'all_books': all_books,
        'books_available': books_available,
        'readers': readers,
        'books_sold': books_sold,
        'book_filter': book_filter
    }

    return render(request, 'home.html', context)

@allowed_user(allowed_roles=['bookreader'])
@login_required(login_url='login')
def bookDetail(request, id):
    book = get_object_or_404(Book, id=id)
    reader = request.user
    

    if request.method == 'POST':
        own = OwnedBook.objects.create(
            reader = reader,
            book = book,
            owned = 'owned'

        )
        book.quantity -= 1
        book.save()
        own.save()
        messages.success(request, "You bought a book")
        
        return redirect("owned-book")
    context = {
        'book': book,
        'reader': reader,
       
    
    }

    return render(request, 'book_detail.html', context)

@allowed_user(allowed_roles=['bookreader'])
@login_required(login_url='login')
def ownedBook(request):
    reader = request.user
    owned_books = reader.owned.all()
    owned_book_count = owned_books.count()

    context = {
        'owned_books': owned_books,
        'owned_book_count': owned_book_count
    }
    
    
    return render(request, 'owned_book.html', context)


@admin_only
@login_required(login_url='login')
def publishBook(request):
    publishForm = PublishBook(request.POST)
    if request.method == 'POST':
        if publishForm.is_valid():
            publishForm.save()
            publishForm = PublishBook()
            messages.success(request, 'A book was published 📚')
            return redirect('home')
            

    context = {
        'publishForm': publishForm
    }
      

    return render(request, 'publish_book.html', context)

@login_required(login_url='login')
def UpdateBook(request, id):
    book = Book.objects.get(id=id)
    publishForm = PublishBook(request.POST or None, instance=book)
    if request.method == 'POST':
        if publishForm.is_valid():
            publishForm.save()
            messages.success(request, 'A book was updated ✒️')
            return redirect('home')

    context = {
        'publishForm': publishForm
    }
      

    return render(request, 'publish_book.html', context)

@login_required(login_url='login')
def DeleteBook(request, id):
    book = Book.objects.get(id=id)
    book.delete()
    messages.info(request, 'A Book was Deleted 😧')
    return redirect('home')

booksforbrain/templates/book_detail.html
{% extends 'main.html' %}

{% block content %}

<style>
    #book-text{
        text-align: center;
    }
</style>


<div class="container">
  
<div class="row p-3 w-100" style="margin: 100px 0 ;">
    <div class="col-md">
      <a href="{% url 'home' %}"><i class="fas fa-arrow-circle-left" style="color: darkslategray; font-size: 30px;"></i></a>
        <div class="card card-body">
           
            <h4 class="d-block m-auto">{{book.book_name}}</h4>
        </div>
        <div class="card card-body my-2">
            <div class="row">
                <div class="col-12 d-md-flex p-md-5">
              <img width="200" class="d-block m-auto m-md-0" src="{{ book.book_image }}">
            <div style="display: block;  padding: 0 5px; margin: 10px auto; ">
                <h4 id='book-text'> Book: {{book.book_name}}</h4>
                <p id='book-text'>Book Author:  {{book.book_author}}</</p>
                <p id='book-text'>Publish date: {{book.date_published}}</</p>
                <p id='book-text'>Price: ${{book.price}}</p></p>
                <p id='book-text'>Genre: {{book.genre}}</p>
                <p id='book-text'>In <span style="color: palevioletred;">Stock</span>: {{ book.quantity }} </p>
                <form action="" method="POST">
                    {% csrf_token %}
                    
                  <button class="btn btn-info d-block m-auto">Buy Book</button>
                 
                    </form>
                    
                
                <p class="my-2">Not your type of book?🤷‍♂️<a href="{% url 'home' %}"> Check other books then</a> </p>
            </div>
                </div>
                <div class="accordion w-100" id="accordionExample">
                    <div class="card" style="background-color: #595666;
                    background-image: linear-gradient(316deg, #cdc1ff 0%, #e5d9f2 74%);">
                      <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                          <button class="btn btn-light d-block m-auto" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Description
                          </button>
                        </h2>
                      </div>
                  
                      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            {{book.description}}</div>
                        </div>
                      </div>
                    </div>
                    
                
            </div>
           
        </div>
    </div>
    
</div>
</div>



{% endblock %}

booksforbrain/templates/home.html
{% extends 'main.html' %}
{% load static %}
 {% block content %}
<style>
  
  
h5{
    margin: 0;
    padding: 0;
    font-size: 35px;
    text-shadow: 1px 2px 2px peru;
    
}

.sold-out{
  position: absolute;
  width: 100px;
  z-index: 1000;
  left: 0;
}
</style>

 <div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">

      <div class="carousel-inner">
        <div class="carousel-item active" id="c-div">
          <img src="{% static 'images/banner.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-block">
            <h5>Welcome to 
                <br>Books for Brain 📚🧠</h5>
            <a class="c-span">Enlighten your brain</a>
             </div>
        </div>
        <div class="carousel-item" id="c-div">
          <img src="{% static 'images/Library-.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-block">
            <h5>Check out all of our amazing books😀</h5>
            <h4 class="c-span">Books just like movies entertain you</h4>
          </div>
        </div>
        <div class="carousel-item" id="c-div">
          <img  src="{% static 'images/book-2.jpg' %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-block">
            <h5>Why don't you get a popc🍿rn while you read our books😎</h5>
            <h4 class="c-span">Just have fun!!.</h4>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    
  </div>
</div>
<div class="container">
    {% include 'status.html' %}
    <br>

    <div class="row p-3 w-100">
        <div class="col-md">
            <div class="card card-body d-flex">
                <h4 style="text-align: center;">Books</h4>
                <form method="GET" style="margin: 0 auto; display: block;">
                  {{ book_filter.form }}
                  <button class="btn btn-dark"><i class="fas fa-search"></i></button>
                </form>
                
            </div>
            <div class="card card-body my-2">
              {% for message in messages %}
					{% if message.tags == 'info' %}
						<div class="alert alert-info mt-2"><p style="text-align: center;">{{ message }}</p></div>
					{% elif message.tags == 'success' %}
					<div class="alert alert-success mt-2"><p style="text-align: center;">{{ message }}</p></div>
					{% endif %}
					{% endfor %}
                <div class="row my-2">
                  {% for books in all_books reversed%}
                  
                  <div class="d-flex col-12 col-lg-4 my-3" style="position: relative;">
                   

                  <img style="height: 150px;" src="{{ books.book_image }}">
                <div class="mx-lg-2 p-2 p-md-0" style="padding: 0 5x; margin: 0 auto; display: block;">
                  {% if books.quantity < 1 %}
                  <img class="sold-out" src="{% static 'images/sold-out.png' %}" >
                  
                  <h4 style="font-size: 15px;">📖 {{ books.book_name }}</h4>
                   {% else %}
                   <h4 style="font-size: 15px;"><a href="{% url 'book-detail' books.id %}">📖 {{ books.book_name }}</a></h4>
                   {% endif %} 
                   <p style="font-size: 13px;">{{ books.book_author }} ✍️</p>
                    <p style="line-height: 5px;">💵 ${{ books.price }}</p>
                    <p style=" font-size: 13px;">📅 {{ books.date_published }}</p>
                    <p style="line-height: 10px; font-size: 13px;">{{ books.genre }} 🔖</p>
                    <p style="line-height: 10px; font-size: 13px;">In <span style="color: palevioletred;">Stock</span>: {{ books.quantity }} 🔖 </p>
                    {% if request.user.is_staff %}
                    <a href="{% url 'update-book' books.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'delete-book' books.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                     {% endif %}
                  </div>
                    </div>

                    {% endfor %}
                </div>
               
            </div>
        </div>
        
    </div>

</div>
</div>
{% endblock %}

booksforbrain/templates/owned_book.html
{% extends 'main.html' %}

{% block content %}

<style>
    #book-text{
        text-align: center;
    }
</style>
<div class="container" style="margin: 100px auto;">
    <div class="row p-3 w-100">
        <div class="col-md">
            <div class="card card-body">
                <h4>Owned Books</h4>
            </div>
            <div class="card card-body my-2">
              {% for message in messages %}
					<div class="alert alert-success mt-2"><p style="text-align: center;">{{ message }}</p></div>
					{% endfor %}
                {% if owned_book_count >= 1 %}
                <div class="row my-2">
                  {% for books in owned_books reversed%}
    
                  <div class="d-flex col col-lg-4 my-3" >
                  <img style="height: 150px;" src="{{ books.book.book_image }}">
                <div style="line-height: 50px;  padding: 0 10px; margin: 0 auto; display: block;">
                    <h4 style="font-size: 18px;">Book: {{ books.book.book_name }}</h4>
                    <p style="line-height: 15px; font-size: 15px;">Book Author: {{ books.book.book_author }}</p>
                    <p style="line-height: 15px; font-size: 15px;">Genre: {{ books.book.genre }} </p>
                    <a href="{{ books.book.book_link }}" class="btn btn-success">Read Book</a>
                </div>
                    </div>
                    
                    
                    {% endfor %}
                </div>
                {% else %}
                    <h2 style="text-align: center;">No owned books yet</h2>
                {% endif %}
               
            </div>
        </div>
        
    </div>
            </div>
           
        </div>
    </div>
    
</div>
</div>



{% endblock %}

booksforbrain/templates/publish_book.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
	<title>Books For Brain -Publish</title>
	<link rel="shortcut icon" href="{% static 'images/brain-fav.png' %}" type="image/x-icon">
	<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
<style>
		body,
		html {
            font-family: 'Montserrat', sans-serif;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #5de6de;
background-image: linear-gradient(315deg, #5de6de 0%, #b58ecc 74%);

		}

     
		.user_card {
			width: 350px;
			margin-top: 100px;
			margin-bottom: auto;
			background-color: #1fd1f9;
background-image: linear-gradient(315deg, #1fd1f9 0%, #b621fe 74%);

			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
            font-weight: 600;
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
            transition: 0.5s ease-in-out;
		}

        .login_btn:hover{
            background: whitesmoke !important;
			color: #33ccff !important;
        }
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

        #id_genre{
            width: 193px;
        }

        #id_description{
            height: 28px;
            width: 193px;
        }

		#changeLI{
    font-family: 'Roboto', sans-serif;
   font-size: 16px;
   display: block;
    font-weight: 400;
    color: #fff;
    transition: 0.2s ease-in-out;
}

#changeLI:hover{
    color: #d5adc8;
    border-bottom:2px solid #861657;
;
}
.logo-text{
    display: block;
    font-size: 20px;
    margin: auto 5px;
    color: #ffc857;
    font-family: 'Roboto', sans-serif;
    text-shadow: 1px 4px 4px #111;
    opacity: 0.8;
}

.menu {
  width: 60px;
  background-color: transparent;
  border: none;
  cursor: pointer;
  display: flex;
  padding: 0;
}
.line {
  fill: none;
  stroke: rgb(212, 45, 45);
  stroke-width: 6;
  transition: stroke-dasharray 600ms cubic-bezier(0.4, 0, 0.2, 1),
    stroke-dashoffset 600ms cubic-bezier(0.4, 0, 0.2, 1);
}
.line1 {
  stroke-dasharray: 60 207;
  stroke-width: 6;
}
.line2 {
  stroke-dasharray: 60 60;
  stroke-width: 6;
}
.line3 {
  stroke-dasharray: 60 207;
  stroke-width: 6;
}
.opened .line1 {
  stroke-dasharray: 90 207;
  stroke-dashoffset: -134;
  stroke-width: 6;
}
.opened .line2 {
  stroke-dasharray: 1 60;
  stroke-dashoffset: -30;
  stroke-width: 6;
}
.opened .line3 {
  stroke-dasharray: 90 207;
  stroke-dashoffset: -134;
  stroke-width: 6;
}


	</style>

</head>
<body>
	
<nav class="navbar navbar-expand-md navbar-light " id="nav" style="background-color: rgb(157,197,195, 0.4);
background-image: linear-gradient(315deg, #9dc5c3 0%, #5e5c5c 74%);">
    <div class="container">
    <a class="navbar-brand d-flex" href="#"><img class="logo" src="{% static 'images/BB_logo.png' %}" ><p class="logo-text">Books for Brain</p></a>
    <button class="navbar-toggler menu" style=" outline: none;" onclick="this.classList.toggle('opened');this.setAttribute('aria-expanded', this.classList.contains('opened'))"  type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Main Menu">
      <svg width="100" height="100" viewBox="0 0 100 100">
        <path class="line line1" d="M 20,29.000046 H 80.000231 C 80.000231,29.000046 94.498839,28.817352 94.532987,66.711331 94.543142,77.980673 90.966081,81.670246 85.259173,81.668997 79.552261,81.667751 75.000211,74.999942 75.000211,74.999942 L 25.000021,25.000058" />
        <path class="line line2" d="M 20,50 H 80" />
        <path class="line line3" d="M 20,70.999954 H 80.000231 C 80.000231,70.999954 94.498839,71.182648 94.532987,33.288669 94.543142,22.019327 90.966081,18.329754 85.259173,18.331003 79.552261,18.332249 75.000211,25.000058 75.000211,25.000058 L 25.000021,74.999942" />
      </svg>
    </button>
    <div class="collapse navbar-collapse my-1 mx-4"  id="navbarNavDropdown" >
      <ul class="navbar-nav" >
        <li class="nav-item active">
          <a id="changeLI" class="nav-link" href="{% url 'home' %}">Books <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_staff %}
        
        <li class="nav-item">
          <a id="changeLI" class="nav-link" href="{% url 'publish-book' %}">Publish</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a id="changeLI" class="nav-link" href="{% url 'owned-book'  %}">Owned Book</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <h5 class="my-1 h5">{{request.user | title}} <i class="fas fa-user-check" style="color: paleturquoise;"></i></h5>
        </li>

        <li class="d-block d-md-none">
          <a href="{% url 'logout' %}" class="btn btn-warning m-3 m-md-0">Logout</a>
        </li>
      </ul>
    </div>
    <a href="{% url 'logout' %}" class="btn btn-warning m-3 m-md-0 d-none d-md-block">Logout</a>
</div>
  </nav>


	<div class="container ">

		<div class="d-flex justify-content-center h-100">
			
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Publish Book</h3>
				</div>
				{% for message in messages %}
		<p class="alert alert-info">{{ message }} 😒</p>
		{% endfor %}
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-images"></i></span>	
							</div>
							{{publishForm.book_image}}
						</div>
	
						<div class="input-group mb-2">
							<div class="input-group-append">
                    <span class="input-group-text"> <i class="fas fa-book"></i></span>	
							</div>
							{{publishForm.book_name}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>								</div>
							{{publishForm.book_author}}
						</div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-link"></i></span>								</div>
							{{publishForm.book_link}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-money-check-alt"></i></span>
							</div>
							{{publishForm.price}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-book"></i></span>
							</div>
							{{publishForm.genre}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-layer-group"></i><span>
							</div>
							{{publishForm.quantity}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-pencil-ruler"></i></span>
							</div>
							{{publishForm.description}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Publish Book">
				   		</div>
					</form>
				</div>
		     {{form.errors}}
		
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
        var form_select = document.getElementsByTagName('select')
        var form_textarea = document.getElementsByTagName('textarea')
		form_fields[1].placeholder='Book Image..';
		form_fields[2].placeholder='Book Title..';
		form_fields[3].placeholder='Book Author..';
		form_fields[4].placeholder='Book Link..';
		form_fields[5].placeholder='Book Price';
		form_fields[6].placeholder='Quantity';
		form_fields[7].placeholder= 'Description';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}

        form_textarea.style += 'form-control'
	</script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	
</body>
</html>

booksforbrain/templates/status.html
<br>
<div class="row w-100">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h6 class="card-title">Books Available</h6>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ books_available }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h6 class="card-title">Books Sold</h6>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ books_sold }}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h6 class="card-title">Readers</h6>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{ readers }}</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>